baseURL: https://eliasgo.netlify.app/
title: Elías Gómez
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Elías Gómez
  avatarURL: {{.Site.BaseURL}}images/avatar.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  csp:
    childsrc: '''self'''
    connectsrc:
      - '''self'''
      - https://www.google-analytics.com
    fontsrc:
      - '''self'''
      - https://fonts.gstatic.com
      - https://cdn.jsdelivr.net/
    formaction: '''self'''
    framesrc: '''self'''
    imgsrc: '''self'''
    objectsrc: '''none'''
    prefetchsrc: '''self'''
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://www.google-analytics.com
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - https://fonts.googleapis.com/
      - https://cdn.jsdelivr.net/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: John Doe's personal website
  enableTwemoji: no
  footerContent: Enter a text here.
  hideColorSchemeToggle: no
  hideCopyright: no
  hideCredits: no
  hideFooter: no
  info:
    - Antropólogo social
    - Afín al estructuralismo genético de Pierre Bourdieu
    - Adepto a "R", y a los análisis estadísticos y espaciales.
  keywords: blog,investigador,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2019
  social:
    - icon: fa fa-github
      name: Github
      url: https://github.com/johndoe/
      weight: 1
    - icon: fa fa-gitlab
      name: Gitlab
      url: https://gitlab.com/johndoe/
      weight: 2
    - icon: fa fa-twitter
      name: Twitter
      url: https://twitter.com/elias3177
      weight: 3
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/elias-g%C3%B3mez-84265332/
      weight: 4
    - icon: fa fa-medium
      name: Medium
      url: https://medium.com/me/stories/public
      weight: 5
    - icon: fa fa-rss
      name: RSS
      rel: alternate
      type: application/rss+xml
      url: https://myhugosite.com/index.xml
      weight: 6
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: Elías
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Proyectos
          url: projects/
          weight: 3
        - name: Contacto
          url: contact/
          weight: 5
  es-es:
    languageName: ':argentina:'
    menu:
      main:
        - name: Sobre
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projetos
          url: projects/
          weight: 3
        - name: Contato
          url: contact/
          weight: 5
    params:
      author: Elías Gómez
      description: Sítio personal de Elías Gómez
      footerContent: Coloque algum texto aqui.
      info: Antropólogo 
      keywords: blog,investigador,analista
    title: Elías Gómez
